### ISSUE TITLE
Copying and moving files will create new destination folders

### ISSUE THREAD

**Issue by GXSZone** [anggrayudi/SimpleStorage#10]
android 10

If you copy or move from folder `A` to folder `B`, folder `B (1)` will be created in the same level directory of `B`. the copied or moved files will be in folder `B (1)`, and there is no such file in folder `B` 

 From translation

**Comment by anggrayudi** [comment]
The current algorithm does not allow copying files into an existed folder, but I will add a capability to resolve the conflict:
* Replace
* Merge
* New Folder
* Cancel

**Comment by anggrayudi** [comment]
Version [0.5.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.5.0) has been released. Please check it.
