### ISSUE TITLE
DocumentFile.makeFile is giving me null and app crashes on some devices

### ISSUE THREAD

**Issue by bonnjalal** [anggrayudi/SimpleStorage#101]
I experienced this issue with Xiaomi redmi note 8 android 10
After some debugging, I found that the issue comes from `parent!!.createFile`. and sometimes from `makeFolder(context, subFolder, mode)`. The DocumentFile can't create the file or the folder on the device even if you have the Uri permission

it does not give me a direct error (that points to the problem on my code) I don't know why, After the app crashes it gives me something like this: 
```
E/ActivityThread: Failed to find provider info for media
E/DatabaseUtils: Writing exception to parcel
```
I have worked around this by modifying the makeFile method like this:
```
fun DocumentFile.makeFile(
    context: Context,
    name: String,
    mimeType: String? = MimeType.UNKNOWN,
    mode: CreateMode = CreateMode.CREATE_NEW
): DocumentFile? {
    if (!isDirectory || !isWritable(context)) {
        return null
    }

     val parent = if (subFolder.isEmpty()) this else {
            makeFolder2(context, subFolder, mode) //?: return null
        }
.......

    if (parent == null) {
        val file = FileDescription(fullFileName, subFolder)
        val createDoc = DocumentFileCompat.createDownloadWithMediaStoreFallback(context, file)

        return DocumentFileCompat.fromUri(context, createDoc!!.uri)
    }

........

    return if (Build.VERSION.SDK_INT > Build.VERSION_CODES.P) {
        val parent1 = parent
        parent!!.createFile(correctMimeType, baseFileName)?.also {
            if (correctMimeType == MimeType.BINARY_FILE && it.name != fullFileName)
                it.renameTo(fullFileName)
        }?: run {
            val file = FileDescription(fullFileName, subFolder)
            DocumentFileCompat.createDownloadWithMediaStoreFallback(context, file)
            parent1!!.findFile(fullFileName)
        }
    } else {
        parent.createFile(correctMimeType, fullFileName)
    }
}
```
I hope you could give us a better solution.

**Comment by anggrayudi** [comment]
What's the library version that caused this issue?

**Comment by bonnjalal** [comment]
> What's the library version that caused this issue?

I use the latest version 1.5.0, but I don't think that the problem from the library itself, I think the problem comes from this package `androidx.documentfile.provider`
This function return null.

```
     /**
     * @return file representing newly created document, or null if failed
     */
    @Nullable
    public abstract DocumentFile createFile(@NonNull String mimeType, @NonNull String displayName);
```
And the same for createFolder.

**Comment by anggrayudi** [comment]
Can you copy `showGrantedUris()` from this file and test it on your project?

https://github.com/anggrayudi/SimpleStorage/blob/7b8a635163f3f795969b6e135811a610170e15db/sample/src/main/java/com/anggrayudi/storage/sample/StorageInfoAdapter.kt#L69

I want to see the list of granted URIs on your Xiaomi device.

**Comment by bonnjalal** [comment]
> Can you copy `showGrantedUris()` from this file and test it on your project?
> 
> https://github.com/anggrayudi/SimpleStorage/blob/7b8a635163f3f795969b6e135811a610170e15db/sample/src/main/java/com/anggrayudi/storage/sample/StorageInfoAdapter.kt#L69
> 
> I want to see the list of granted URIs on your Xiaomi device.

I tested it and this is what it gives me:
Granted URIs [/storage/emulated/0/Download]

------
I already testing if the app have access to the chosen URI by user before perform anything else. with this fun:
```
private fun isStorageUriGranted(storageId: String, basePath: String): Boolean{
        val root = createDocumentUri(storageId, basePath)
        val contentResolver = applicationContext.contentResolver

        return contentResolver.persistedUriPermissions.any {

            it.isReadPermission && it.isWritePermission && it.uri == root
        }
}

```

**Comment by anggrayudi** [comment]
I see... So, your URI is only applicable to `Download` folder, but you were trying to make folder outside this directory. If you want to create folders inside this path, please use `DocumentFileCompat.fromPublicFolder()`:

```kotlin
val download = DocumentFileCompat.fromPublicFolder(this, PublicDirectory.DOWNLOADS, requiresWriteAccess = true) ?: return
val newFolder = download.makeFolder(this, "Example") ?: return
```

You'll not be able to access `parent` from path `/storage/emulated/0/Download`, because your URI is only limited to this path, hence the parent is always null.

But if you want wider access for Android 10, please grant access to the root path of the storage partition, in this case `/storage/emulated/0`. In Android 10, if your granted URI is this path, then you'll be able to create folders anywhere in that storage partition.

**Comment by lrq3000** [comment]
```
val download = DocumentFileCompat.fromPublicFolder(this, PublicDirectory.DOWNLOADS, requiresWriteAccess = true) ?: return
val newFolder = download.makeFolder(this, "Example") ?: return
```

This appears to not work anymore, failing with a `java.lang.NullPointerException`.

**Comment by lrq3000** [comment]
In fact, the following causes a NullPointerException too on Android 11:

```
val download = DocumentFileCompat.fromPublicFolder(activity, PublicDirectory.DOWNLOADS, requiresWriteAccess=true)
Log.d("MyApp", "Debugv Can write to Downloads? " + download!!.canModify(activity))
```
