### ISSUE TITLE
File access not possible after clearing app data

### ISSUE THREAD

**Issue by cyberdreamandroid** [anggrayudi/SimpleStorage#102]
Library version: 1.5.0
OS version: Android 10
Device model: Nvidia Shield

I don'tknow if this is an Android issue or an issue of the library. I am able to save and read a file using this command:
MediaFile mediaFile = MediaStoreCompat.fromRelativePath(context, Environment.DIRECTORY_DOWNLOADS, fileName);
If I clear app storage data and run the same query again, I get a FileNotFound exception. Permissions to read/write storag are granted of course. Any idea?

**Comment by anggrayudi** [comment]
You will lost access to your files once the app is uninstalled or its data are cleared. The files might still be there, but you can't query them. This is OS level issue, not the library. `MediaStore` is only appropriate for **write and forget** cases. I explained more about this on issue #103.

BTW, if you have URI access for read & write permissions to that folder, then you can use extension function `DocumentFile.makeFile()` and `DocumentFile.makeFolder()`.
