### ISSUE TITLE
openFilePicker does not support EXTRA_MIME_TYPES

### ISSUE THREAD

**Issue by adsamcik** [anggrayudi/SimpleStorage#11]
It is currently not possible (to my knowledge) to request multiple mime types from file picker.

https://developer.android.com/reference/android/content/Intent.html#EXTRA_MIME_TYPES

**Comment by anggrayudi** [comment]
The Android framework itself does not support `Intent.EXTRA_MIME_TYPES`, as described here: https://stackoverflow.com/q/21045091/3922207

What you can do is filtering files via single mime type, for example:
`simpleStorage.openFilePicker(requestCode, "video/*")`
