### ISSUE TITLE
How to overwrite/truncate an already existing file?

### ISSUE THREAD

**Issue by lrq3000** [anggrayudi/SimpleStorage#111]
Just a quick question, in case you have a better solution than I found:

I tried to reopen a file (not a folder, but a file inside a folder with granted permissions) to overwrite its whole content new content. The problem is that despite specifying I do not want to append, the content I write is placed at the start of the file over the old content, but if I write a shorter string than is in the file, I get the new string + what remains of the old string.

Here is what I used:

```kotlin
val file = DocumentFileCompat.fromFullPath(appContext, path!!, requiresWriteAccess=true, considerRawFile=true)
file?.openOutputStream(appContext, append=false)
out?.let { out ->
    try {
        out!!.write(json.toByteArray(Charsets.UTF_8))
    } catch (e: Exception) {
        Log.d("MyApp", "Debugv unable to write: " + e.stackTraceToString())
    } finally {
        out?.close()
    }
}
```

When using `makeFile()`, there is a `CreateMode.REPLACE` constant that allows to recreate the file first. But here there is no such argument in the functions I call.

What I ended up doing was the following, which is to use `recreateFile()` before `openOutputStream()`:

```kotlin
val file = DocumentFileCompat.fromFullPath(appContext, path!!, requiresWriteAccess=true, considerRawFile=true)
file?.recreateFile(appContext)  // erase content first by recreating file
file?.openOutputStream(appContext, append=false)
[rest of the code...]
```

Is this the only way, or am I missing another more elegant way to truncate/replace the file's content?

Thank you again very much!

**Comment by anggrayudi** [comment]
Did you mean `CreateMode.REPLACE` in function `DocumentFileCompat.fromFullPath()`? If so, then it is expected to not have `CreateMode` parameter in this function. Because `fromFullPath()` is intended to retrieve accessible folders/files only. Your approach to recreate the file is already correct.

BTW, thanks for your donation that I've received today 🙏.

**Comment by lrq3000** [comment]
Ok awesome, thank you very much, I have updated my code with your suggestion!

You're welcome, sorry it's just a small donation, I'm a bit short on money currently, but honestly you should get more donations given the great service you are doing to the Android dev community! I guess it's just that your library isn't well known yet.

I am implementing SimpleStorage in at least one app and maybe a second one after, I'll let you know when it's done, so you can add to the README as other examples of practical implementations if you want :-)
