### ISSUE TITLE
Awesome 

### ISSUE THREAD

**Issue by AaronJerome1** [anggrayudi/SimpleStorage#124]
**What feature you want to suggest?**
[Explain your idea and how it can help Simple Storage to be better]

**Your solution**
[Expected solution for the feature, if any]

**Your current alternative**
[Do you have any alternative or workaround to overcome the feature that's not available yet?]

**Comment by anggrayudi** [comment]
Thanks for using this library. I hope it helps you a lot. Don't forget to give a star to this repo if you like it.
