### ISSUE TITLE
Not working on complieSDK/targetSDK 33 

### ISSUE THREAD

**Issue by nguyencongbinh** [anggrayudi/SimpleStorage#128]
Please update the lib with complieSDK/targetSDK 33.

**Comment by anggrayudi** [comment]
Aren you sure? This library already uses v33 since last year. Check this commit: https://github.com/anggrayudi/SimpleStorage/commit/3b3a8a3b396998e88503289629798c3aadd315ec

**Comment by nguyencongbinh** [comment]
@anggrayudi,
Sorry, It is because I looked on Java example file and does not see code for checking permissions like  
Manifest.permission.READ_MEDIA_IMAGES, Manifest.permission.READ_MEDIA_AUDIO, Manifest.permission.READ_MEDIA_VIDEO

**Comment by anggrayudi** [comment]
Maybe something wrong with your AGP/Gradle configs. I'll close this issue now.
