### ISSUE TITLE
multiple mime type

### ISSUE THREAD

**Issue by emreesen27** [anggrayudi/SimpleStorage#138]
Is it possible to make the query parametric? Or is there a solution to add more than one mimeType?

mediaStore.getMediaFromMimeType(mediaType, "image/png")

If I only want to find png and jpeg images, how can I proceed?

**Comment by anggrayudi** [comment]
Have you tried this?
```
mediaStore.getMediaFromMimeType(mediaType, "image/*")
```
Try the asterisk `*` suffix
