### ISSUE TITLE
How can I specify to obtain files of certain formats, and then customize the view to display these files, such as PDF files?

### ISSUE THREAD

**Issue by AldenLei** [anggrayudi/SimpleStorage#143]
Library version: 1.5.6
OS version: [Android 13]
Device model: [Oppo]

I've tried reading the code and the documentation but I can't filter some specified files, like pdf, epub, or html. Can this framework achieve this? Thank you very much.

**Comment by anggrayudi** [comment]
Hi, what function are you using to filter the desired files? Is it `search()`, `openFilePicker()`, or any functions? If you want to filter certain files, you can play with mime type: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

For example, picking files will be:
```kotlin
storageHelper.openFilePicker(filterMimeTypes = arrayOf("application/pdf", "text/html"))
```

**Comment by AldenLei** [comment]
Hi,
thx for your fast answer.
I use the copyFileTo function but ANR;
my project is java,It's my code:
//rootPath:/data/user/0/com.xxx.xxx/cache/xxx/xxx/file
  DocumentFile targetDocumentFile =  DocumentFile.fromFile(new File(rootPath));
//documentFile uri:  content://com.android.providers.media.documents/document/document%3A27286
  DocumentFileUtils.copyFileTo(documentFile,this,targetDocumentFile,null,fileCallback);

the error log:
![WX20240621-180638@2x](https://github.com/anggrayudi/SimpleStorage/assets/21965551/98a17f6f-b8f1-4fbf-bdb4-c26e51af9123)

**Comment by anggrayudi** [comment]
If you look into `copyFileTo()` annotation, it has `@WorkerThread` which means you should execute it in the background thread. If you call that function in the UI thread, it will cause ANR.
