### ISSUE TITLE
[Q] Java example to open directory chooser and list files in nested arraylist

### ISSUE THREAD

**Issue by omkar-tenkale** [anggrayudi/SimpleStorage#15]
I'm trying to allow user to choose a folder from SAF and display the files in chosen folder

But I couldn't find enough documentation

I only want to read the folder contents
Is write storage permission required?
Is Request Storage Access needed?

After user chooses the folder how can i access it?
`DocumentFileCompat.fromSimplePath()`
might be the solution but I'm failing to come to a solution

**Comment by anggrayudi** [comment]
Have you tried [`SimpleStorageHelper`](https://github.com/anggrayudi/SimpleStorage#simplestoragehelper)?
This class will help you a lot.

**Comment by omkar-tenkale** [comment]
SimpleStorageHelper  has some pretty useful methods to copy files or even the whole folders 
Thanks!
