### ISSUE TITLE
Example to create a file in "Documents" folder that works for all versions

### ISSUE THREAD

**Issue by amarilindra** [anggrayudi/SimpleStorage#19]
`createDownload` function inside `MediaStoreCompat` has the hardcoded folder name Environment.DIRECTORY_DOWNLOADS

Also, `createDownload` **@RequiresApi(Build.VERSION_CODES.Q)**

I also tried `createDownloadWithMediaStoreFallback` from `DocumentFileCompat` which also stores the file in Downloads folder

So, how can I create a file inside the public **Documents** folder for all versions?

**Comment by anggrayudi** [comment]
We can't, because there's no `android.provider.MediaStore.Documents`:

![image](https://user-images.githubusercontent.com/12292380/115370493-50d20c80-a1f3-11eb-8f2f-d3c6d6c8375f.png)
