### ISSUE TITLE
.bin

### ISSUE THREAD

**Issue by ueen** [anggrayudi/SimpleStorage#21]
i use
`DocumentFileUtils.moveFileTo(DocumentFile.fromFile(file), this, Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), name, new FileCallback() `

the source file is a jpg but doesnt have a file extension (_image_) the new `name` contains an extension (_image.jpg_) but what i get in the downloads folder is _image.jpg_**.bin**

**Comment by anggrayudi** [comment]
This is expected. A file type is treated as unknown if:
* It has no extension.
* Or the mime type is null (detected via `documentFile.type`).

Android 10+ reads these unknown files as binary files, thus the system will append extension ***.bin** whenever you create a file. What you can do is checking whether the target filename ends with ***.bin**. If so, just rename it with `renameTo()`. You can change the file name, but please be aware that current Simple Storage does not support changing the mime type. I'll check if changing mime type of existed files is possible. If yes, I'll add a function `changeMimeTypeTo()` in Simple Storage 0.5.3.

**Comment by anggrayudi** [comment]
BTW, having a function with these parameters seems a good idea:
```java
FileDescription desc = new FileDescription(newName, newMimeType);
DocumentFileUtils.moveFileTo(sourceFile, context, targetFolder, desc, callback);
```
So you don't need to rename the file after it is moved.

**Comment by ueen** [comment]
yea that would be a good idea, can you implement it?

**Comment by ueen** [comment]
i fixed it for me by adding a extension to the sourceFile, i guess thats the easiest solution.
