### ISSUE TITLE
onCompleted

### ISSUE THREAD

**Issue by ueen** [anggrayudi/SimpleStorage#22]
i use `DocumentFileUtils.moveFileTo`
and in the
```
 @Override
 public void onCompleted(@NotNull Object file) {
        DocumentFile documentFile = (DocumentFile) file;
        ...
        intent.setDataAndType(file.getUri(), fileHeader.mime);
```
this always gives my an FileUriExposedException for exposing beyond the app (`file:///`), how do i get a valid FileProvider from inside onCompleted?

**Comment by anggrayudi** [comment]
Have you tried this?
```java
DocumentFile documentFile = (DocumentFile) file;
Uri uri = FileProvider.getUriForFile(context, authority, documentFile.path);
intent.setDataAndType(uri, fileHeader.mime);
```
Source: https://stackoverflow.com/a/38858040/3922207

**Comment by ueen** [comment]
of course, the problem is, that DocumentFile doesnt have path
_"A single document may appear as the child of multiple directories, so it doesn't inherently know who its parent is. That is, documents don't have a strong notion of path."_
https://developer.android.com/reference/androidx/documentfile/provider/DocumentFile

I saw that you have a File in DocumentFileExt `callback.onCompleted(DocumentFile.fromFile(targetFile))` why arent you just returning the actual File? Then i could just `Uri uri = FileProvider.getUriForFile(context, authority, targetFile);`

**Comment by anggrayudi** [comment]
> Why arent you just returning the actual File?

`DocumentFile` is more general and has richer Kotlin extension functions than `java.io.File`. You can check whether it is a `java.io.File` via `DocumentFileUtils#isRawFile`, or you can convert it like this:
```java
File file = DocumentFileUtils.toRawFile(documentFile);`
// Variable 'file' can be null if isRawFile == false
```

**Comment by ueen** [comment]
Thats it, thanks!
