### ISSUE TITLE
openFolderPickerOnceGranted

### ISSUE THREAD

**Issue by ueen** [anggrayudi/SimpleStorage#23]
i use `new SimpleStorageHelper(this).requestStorageAccess(SimpleStorageHelper.REQUEST_CODE_STORAGE_ACCESS,false);`
but the folder picker opens afterwards anyway

**Comment by anggrayudi** [comment]
SimpleStorageHelper must not be used like that. Keep it as a field:

```kotlin
private lateinit var storageHelper: SimpleStorageHelper

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)
    storageHelper.storage.onActivityResult(requestCode, resultCode, data)
}
```

Follow this instruction: https://github.com/anggrayudi/SimpleStorage#simplestoragehelper

**Comment by ueen** [comment]
Snapdrop app seems to work without requesting permissions 🤷🤷 so I'll close this
