### ISSUE TITLE
CANNOT_CREATE_FILE_IN_TARGET

### ISSUE THREAD

**Issue by ueen** [anggrayudi/SimpleStorage#24]
If copying the same file to same destionation with

```
@Override
            public void onConflict(@NotNull DocumentFile destinationFile, @NotNull FileCallback.FileConflictAction action) {
                action.confirmResolution(ConflictResolution.REPLACE);
            }
```
the app tombstones
Works only the first time...

**Comment by anggrayudi** [comment]
Can you put the stacktrace here?

**Comment by ueen** [comment]
I'll put the commit in this PR https://github.com/fm-sys/snapdrop-android/pull/76

Its not a stacktrace, it just freezes and then tombstones...

**Comment by anggrayudi** [comment]
Did you call `moveFileTo()` from the main thread? If you look into the source code, it should be invoked from the background thread. `moveFileTo()` is annotated by `@WorkerThread`.

**Comment by ueen** [comment]
intresting, yea i did, where should i call it, via Worker?

**Comment by anggrayudi** [comment]
It is up to your app architecture. You can use `java.lang.Thread`, [RxJava](https://github.com/ReactiveX/RxAndroid), or [`ExecutorService`](http://tutorials.jenkov.com/java-util-concurrent/executorservice.html).

**Comment by ueen** [comment]
Its strange, no i removed the onconflict, the frist 5 files (same file) worked just fine, but then i get `CANNOT_CREATE_FILE_IN_TARGET`
https://github.com/fm-sys/snapdrop-android/pull/76

**Comment by anggrayudi** [comment]
Can you jump into this code? Check if it is called via breakpoint.

![image](https://user-images.githubusercontent.com/12292380/116447209-ed467f80-a881-11eb-8fa8-9e87dd77d8bd.png)

If it is called, this means the Android system cannot delete the existed file in the destination.

**Comment by ueen** [comment]
no i didnt add onConflict, but it might be solved now that i added ExecutorService, have to test a bit more, sorry for being annoying, i didnt get that i had to use async...

**Comment by ueen** [comment]
wait a sec, it still happens sometimes, i'll add some breakpoints

**Comment by ueen** [comment]
The breakpoints somehow dont work, if i rename the file it works again... 🤷

**Comment by anggrayudi** [comment]
Can you breakpoint all lines that contain `CANNOT_CREATE_FILE_IN_TARGET` in `DocumentFileUtils`? Let's see which line is triggered.

**Comment by ueen** [comment]
its somehow compiled, i cant...

**Comment by anggrayudi** [comment]
Put your breakpoint here. Let's see whether it is triggered:

![image](https://user-images.githubusercontent.com/12292380/116454609-61852100-a88a-11eb-956f-32fc30396393.png)

**Comment by ueen** [comment]
nope

**Comment by anggrayudi** [comment]
What about this line? Let's test it with breakpoint.

![image](https://user-images.githubusercontent.com/12292380/116456007-f0466d80-a88b-11eb-92dd-7bbcfcaa13c0.png)

**Comment by ueen** [comment]
Thats only called in onCompleted so that cant be it, i think the breakpoints are jusrt not working in the library..

**Comment by anggrayudi** [comment]
Yes, I know. But can you put a breakpoint there?

**Comment by ueen** [comment]
Oh shit i never used breakpoints before, had to run with debug bug 🤦🤦🤦

**Comment by anggrayudi** [comment]
I've just realized that Snapdrop does not use any Kotlin dependency. You need to add it to make the breakpoint works.

**Comment by ueen** [comment]
oh no it does now i was just running the app instead of debug

its this one
```
private fun DocumentFile.createTargetFile(
    context: Context,
    targetFolder: DocumentFile,
    newFilenameInTargetPath: String?,
    callback: FileCallback
): DocumentFile? {
    val targetFile = targetFolder.makeFile(context, newFilenameInTargetPath ?: name.orEmpty(), type)
    if (targetFile == null) {
        callback.onFailed(FileCallback.ErrorCode.CANNOT_CREATE_FILE_IN_TARGET)
    }
    return targetFile
}
```

**Comment by anggrayudi** [comment]
I've found the root cause. The fixes will be on v0.5.3.

**Comment by ueen** [comment]
Awesome, looking forward to Test it :)

**Comment by anggrayudi** [comment]
Can you try `0.5.3-SNAPSHOT` version?

**Comment by ueen** [comment]
Still persisting  unfortunately , i'll debug again if its the same breakpoint

**Comment by ueen** [comment]
investigated further
this is the issue
```
if (isRawFile) {
        // RawDocumentFile does not avoid duplicate file name, but TreeDocumentFile does.
        return DocumentFile.fromFile(toRawFile()?.makeFile(cleanName, mimeType) ?: return null)
    }
```

**Comment by ueen** [comment]
the issue is further down at `isRawFile -> File(uri.path ?: return null)`

**Comment by anggrayudi** [comment]
Can you refresh your dependency? I've released the [snapshot](https://oss.sonatype.org/#nexus-search;gav~com.anggrayudi~storage~~~~kw,versionexpand) again. Follow this instruction to refresh snapshots: https://stackoverflow.com/a/62085606/3922207

**Comment by ueen** [comment]
<img width="784" alt="Bildschirmfoto 2021-04-29 um 13 28 47" src="https://user-images.githubusercontent.com/5067479/116543979-d9853280-a8ee-11eb-878b-2c3c705048f8.png">
i dont know is this the latest?
It doesnt work as of now

**Comment by ueen** [comment]
It seems to have something to do with the filename, as changing it makes it work, i dont know, also i'm on Android 11, maybe the persissions have something to do with it also? If you like can get the fork and test it yourself if that makes it easier https://github.com/ueen/snapdrop-android/tree/patch-7

Steps to reproduce
1) install debug app
2) open https://snapdrop.net/
3) send files (small pictures, the same repeatedly), the first few should work
4) restart or reinstall app and try to send the same files, sometimes it should stop working (you see that in the log and that the snackbar isnt displayed after saving the file in the app)

Hope this was comprehensible, i can also test if theres a new snapshot, but maybe you can figure out the issue this way more easily :)

**Comment by ueen** [comment]
Or maybe this is an issue of multithreading? I read somewhere only one thread can access the filesystem at a time, you can look at the implementation, I just execute on `ExecutorService executor = Executors.newSingleThreadExecutor();`

**Comment by anggrayudi** [comment]
Found the root cause. You did not ask users to grant URI permissions for read & write access. Read: https://github.com/anggrayudi/SimpleStorage#request-storage-access

![image](https://user-images.githubusercontent.com/12292380/116558575-c5125b80-a929-11eb-8d26-5a8d8e3dfc0e.png)

To make it work on Android 10+ without requesting URI permissions, you have to use `MediaFile` like this:

![image](https://user-images.githubusercontent.com/12292380/116558766-fa1eae00-a929-11eb-8f45-e5407770799a.png)

Update the snapshot to try this new `moveFileTo()`.

**Comment by ueen** [comment]
Thanks, I'll try, this just makes no sense to me, when you need permissions and when you do not... 🙈

**Comment by ueen** [comment]
Somehow it really hard to update the snapshot for me, meaning i cant do it, i was just wondering, cant you somehow to this internally in `createDownload`?

In `onCompleted` if have this now (looks better in kotlin i'm sure)

```
Uri uri = null;

                if (file instanceof MediaFile) {
                    MediaFile mediaFile = (MediaFile) file;
                    uri = mediaFile.getUri();
                } else if (file instanceof DocumentFile) {
                    DocumentFile documentFile = (DocumentFile) file;
                    uri = DocumentFileUtils.isRawFile(documentFile) ? FileProvider.getUriForFile(MainActivity.this, getApplicationContext().getPackageName() + ".provider", DocumentFileUtils.toRawFile(documentFile)) : documentFile.getUri();
                }

                Uri finalUri = uri;
                //UI Thread
                handler.post(() -> fileDownloadedIntent(finalUri, fileHeader));
```

**Comment by anggrayudi** [comment]
Use this to refresh your dependencies: https://stackoverflow.com/a/62085606/3922207

> cant you somehow to this internally in createDownload (the Build.Version check)?

What is your expectation?

**Comment by ueen** [comment]
To use only one moveFileTo, if possible

**Comment by anggrayudi** [comment]
> To use only one moveFileTo

It's not possible, because the way we handle `DocumentFile` and `MediaFile` are very different.

**Comment by ueen** [comment]
```
    public void copyTempToDownloads(JavaScriptInterface.FileHeader fileHeader) {

        executor.execute(() -> {

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                MediaFile newFile = MediaStoreCompat.createDownload(this, new FileDescription(fileHeader.name,"",fileHeader.mime), true);
                if (newFile != null) {
                    DocumentFileUtils.moveFileTo(DocumentFile.fromFile(fileHeader.path), this, newFile, fileCallback(fileHeader));
                }
            } else {
                DocumentFileUtils.moveFileTo(DocumentFile.fromFile(fileHeader.path), this, Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), fileHeader.name, fileCallback(fileHeader));
            }


        });

    }

    private FileCallback fileCallback(JavaScriptInterface.FileHeader fileHeader) {
        return new FileCallback() {
            @Override
            public void onFailed(@NotNull FileCallback.ErrorCode errorCode) {
                Log.d("SimpleStorage", errorCode.toString());
                //UI Thread
                handler.post(() -> Toast.makeText(MainActivity.this, errorCode.toString(), Toast.LENGTH_SHORT).show());
            }

            @Override
            public void onCompleted(@NotNull Object file) {
                Uri uri = null;

                if (file instanceof MediaFile) {
                    MediaFile mediaFile = (MediaFile) file;
                    uri = mediaFile.getUri();
                } else if (file instanceof DocumentFile) {
                    DocumentFile documentFile = (DocumentFile) file;
                    uri = DocumentFileUtils.isRawFile(documentFile) ? FileProvider.getUriForFile(MainActivity.this, getApplicationContext().getPackageName() + ".provider", DocumentFileUtils.toRawFile(documentFile)) : documentFile.getUri();
                }

                Uri finalUri = uri;
                //UI Thread
                handler.post(() -> fileDownloadedIntent(finalUri, fileHeader));

            }
        };
    }
```

still crashes on `newFile` with
```
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:178)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
        at android.content.ContentResolver.insert(ContentResolver.java:2152)
        at android.content.ContentResolver.insert(ContentResolver.java:2114)
        at com.anggrayudi.storage.media.MediaStoreCompat.createMedia(MediaStoreCompat.kt:128)
        at com.anggrayudi.storage.media.MediaStoreCompat.createDownload(MediaStoreCompat.kt:36)
        at com.fmsys.snapdrop.MainActivity.lambda$copyTempToDownloads$3$MainActivity(MainActivity.java:528)
        at com.fmsys.snapdrop.-$$Lambda$MainActivity$KJqT4INiI293_-FC4fqu2v9dCdE.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by ueen** [comment]
renaming them works, its not about the permissions, its something else, i also tried to unistall an reinstall the app

**Comment by ueen** [comment]
actually its just specific filenames that dont work

**Comment by ueen** [comment]
I found something, this only happens if i send/save the file, delete it in the filemanager app (Samsung default) and then send another file with the same filename!!

**Comment by ueen** [comment]
Did you encounter anything like this before?

**Comment by ueen** [comment]
Can you reproduce it? https://github.com/fm-sys/snapdrop-android/pull/76
1. send file from pc https://snapdrop.net/
2. save in app
3. go to filemanager
4. delete file in downloads folder
5. open app and send file again

**apk** https://github.com/fm-sys/snapdrop-android/suites/2613901505/artifacts/57251951

**Comment by anggrayudi** [comment]
> Can you reproduce it? [fm-sys/snapdrop-android#76](https://github.com/fm-sys/snapdrop-android/pull/76)
> 
> 1. send file from pc https://snapdrop.net/
> 2. save in app
> 3. go to filemanager
> 4. delete file in downloads folder
> 5. open app and send file again
> 
> **apk** https://github.com/fm-sys/snapdrop-android/suites/2613901505/artifacts/57251951

Did not happened after I add this check into `MediaStoreCompat`:
```kotlin
if (existingMedia?.openInputStream()?.use { it.available() == 0 } == true) {
```

Update your snapshots again. BTW, what's your OS version?

**Comment by anggrayudi** [comment]
Tested on Android 10:
* Redmi Note 7
* Samsung A21

**Comment by ueen** [comment]
Have Samsung A40 Android 11

**Comment by anggrayudi** [comment]
Please test on different devices with Android 11, e.g. Xiaomi or Oppo.

> Have Samsung A40 Android 11

**Comment by ueen** [comment]
have no other devices, only samsung, but i guess the A40 is a popular device so if it doesnt work, its no real use, i'll test with ne new snapshot again, wait a sec

**Comment by ueen** [comment]
So i can confirm it works finally! great work, thank you very much, the handling storage is really no fun, did you get a chance to look at the other issue with php?

**Comment by ueen** [comment]
`DocumentFileUtils.moveFileTo(DocumentFile.fromFile(fileHeader.getTempFile()), this, Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), fileDescription, fileCallback(fileHeader));`


Has the send-delete-send issue with `CANNOT_CREATE_FILE_IN_TARGET`

**Comment by ueen** [comment]
Can you add this magic line `if (existingMedia?.openInputStream()?.use { it.available() == 0 } == true) {` to the regular moveFileTo without MediaFile but with fileDescription as well (see above)?

**Comment by anggrayudi** [comment]
What is your purpose by adding `if (existingMedia?.openInputStream()?.use { it.available() == 0 } == true) {`?

**Comment by ueen** [comment]
I think the problem is in FileExt 
```
return try {
        File(parent, autoIncrementFileName(fullFileName)).let { if (it.createNewFile()) it else null }
    } catch (e: IOException) {
        null
    }
```
`createNewFile - false if the named file already exists` https://developer.android.com/reference/java/io/File#createNewFile()

The file somehow presists after it is deleted in the filemanager (maybe as an empty reference or something) 

So a solution would be to rename like image-1.jpg or check (if possible) if this is a empty reference

**Comment by ueen** [comment]
https://stackoverflow.com/questions/53048049/file-createnewfile-always-returns-false-even-if-the-file-is-newly-created

**Comment by anggrayudi** [comment]
Added this check on the latest snapshot, please try.

![image](https://user-images.githubusercontent.com/12292380/116676895-bed7ba00-a9d1-11eb-9efc-3c2eb0d48f50.png)

**Comment by anggrayudi** [comment]
Tested on Redmi Note 4 (Android 7). Worked.

**Comment by ueen** [comment]
Still no luck on Android 11, can you maybe make `isFile` and `length` vars so i can debug with breakpoints?

**Comment by ueen** [comment]
it length is 0 and isFile is also false, createNewFile is also false, this makes no sense...

**Comment by ueen** [comment]
The difference is in createNewFile, if i rename the file and send again it returns true, a deleted file returns false...

**Comment by anggrayudi** [comment]
IDK whether this is a bug on Android 11. Can you send me the result of the following code, according to your device?
```kotlin
        val downloadFile = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        val downloads = DocumentFileCompat.fromPublicFolder(this, PublicDirectory.DOWNLOADS, requiresWriteAccess = true)
        Log.d(TAG, downloads.isRawFile)
        Log.d(TAG, downloads.canRead())
        Log.d(TAG, downloads.canWrite())
        Log.d(TAG, SimpleStorage.hasStoragePermission(this))
        Log.d(TAG, Environment.isExternalStorageManager(downloadFile))
        Log.d(TAG, SimpleStorage.hasStorageAccess(this, downloadFile.absolutePath, true))
```

**Comment by ueen** [comment]
or can you just (check length == 0 && !exists) and then return `it`?

**Comment by ueen** [comment]
> ```kotlin
>  val downloadFile = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
>         val downloads = DocumentFileCompat.fromPublicFolder(this, PublicDirectory.DOWNLOADS, requiresWriteAccess = true)
>         Log.d(TAG, downloads.isRawFile) `true`
>         Log.d(TAG, downloads.canRead()) `true`
>         Log.d(TAG, downloads.canWrite()) `true`
>         Log.d(TAG, SimpleStorage.hasStoragePermission(this)) `true`
>         Log.d(TAG, Environment.isExternalStorageManager(downloadFile)) `false`
>         Log.d(TAG, SimpleStorage.hasStorageAccess(this, downloadFile.absolutePath, true)) `false`
> ```

**Comment by ueen** [comment]
I dont think this is a permission issue, if i rename the file it works, its somehow an issue of File and createNewFile if a file with the same filename was deleted in the directory before

**Comment by anggrayudi** [comment]
Thanks. I've found the bug. `downloads.canWrite()` should `false` because it is a raw file (`java.io.File`) and `Environment.isExternalStorageManager(downloadFile)` returns `false`. `downloads.canWrite()` is buggy on some devices. I think we should not rely on it. I'll add the fixes.

Can you report `downloads.canWrite()` to Google while I'm fixing this bug?

**Comment by ueen** [comment]
I should also mention that ScopedStorage is ignored in the manifest of the SnapDrop app, it's really strange that I can write without permission at all

**Comment by ueen** [comment]
But how does this relate to createNewFile? That's where the null is returned...

**Comment by anggrayudi** [comment]
> But how does this relate to createNewFile?

That's because `Environment.isExternalStorageManager(downloadFile)` returns `false`, so you don't have full disk access, thus you cannot create files properly. Read: https://developer.android.com/reference/android/os/Environment#isExternalStorageManager(java.io.File)

You can create files without problem if `isExternalStorageManager()` returns `true`.

**Comment by ueen** [comment]
But I can create files without a problem! 

Only is I delete them I can't write another file with the same filename!

**Comment by ueen** [comment]
> Added this check on the latest snapshot, please try.
> 
> ![image](https://user-images.githubusercontent.com/12292380/116676895-bed7ba00-a9d1-11eb-9efc-3c2eb0d48f50.png)

Can you change this to (createNewFile || (length == 0 && !exists)) so I can test something?

**Comment by anggrayudi** [comment]
Current problem you're facing because `isExternalStorageManager()` returns `false`. Let's see after I add the fixes.

Please avoid using `java.io.File` if `isExternalStorageManager()` returns `false`, because it will lead to another bug.

> Can you change this to (createNewFile || (length == 0 && !exists)) so I can test something?

`length()` always zero if the file does not exist. So it is useless.

**Comment by ueen** [comment]
Got a reply on SO https://stackoverflow.com/questions/67332280/android-file-createnewfile-false-but-exists-also-false/67332774#67332774 don't know if this helps

**Comment by anggrayudi** [comment]
As stated from SO:
> Mostly on an Android 11 device if the file exists() but you cannot `File.list()` it and not read or write it then the MediaStore still has an entry for the file.

`autoIncrementFileName()` rely on `File.list()`, but because `File.list()` returns empty list, thus creating files is impossible. Try requesting full disk access, and `File.list()` will return non-empty file list. Follow this instruction: https://developer.android.com/training/data-storage/manage-all-files

**Comment by ueen** [comment]
Ok then I'll use MediaFile for 10+ because I don't really need full disk access, only to add a file to downloads...

**Comment by ueen** [comment]
Is this an issue below API 10?

**Comment by anggrayudi** [comment]
Which issue? I think we have many issues on this thread. 😅

**Comment by ueen** [comment]
Haha, no the main issue https://github.com/anggrayudi/SimpleStorage/issues/24#issuecomment-829346410

**Comment by ueen** [comment]
Also when will 0.5.3 be released? :)

**Comment by anggrayudi** [comment]
0.5.3 has been released. Wait for several minutes until it is available on Maven.

**Comment by ueen** [comment]
Thanks for the hard work! I read on reddit that on android 11 all IO operation go through SAF so there shouldn't be a speed difference between using MediaFile and using a different method or did you find something different?

**Comment by anggrayudi** [comment]
Normal `moveFileTo()` uses `renameTo()` when possible, but it requires storage access. `renameTo()` can move 1GB file in a second when the source and target files are located in the same file partition.
