### ISSUE TITLE
.php

### ISSUE THREAD

**Issue by ueen** [anggrayudi/SimpleStorage#25]
`test.php` is saved as `test.php.bin` with 0.5.2 and `DocumentFileUtils.moveFileTo`
temp path was: `/data/user/0/com.fmsys.snapdrop/cache/test8924247327830305609.php`
mime is: `text/php`

```
DocumentFileUtils.moveFileTo(DocumentFile.fromFile(tempFile), this, Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "test.php", new FileCallback(...));
```

**Comment by anggrayudi** [comment]
I've uploaded a new snapshot, please update your project.

**Comment by ueen** [comment]
Does that work on older devices without MediaFile as well?

**Comment by ueen** [comment]
yep, thanks, will test

**Comment by anggrayudi** [comment]
> Does that work on older devices without MediaFile as well?

As long as you have storage access, yes, it will work on all OS versions.
