### ISSUE TITLE
Merging folders with replacing files

### ISSUE THREAD

**Issue by DaiZrei** [anggrayudi/SimpleStorage#26]
Hello! When I copy a folder to a directory containing a folder of the same name, a conflict arises that can be resolved with "Replace, Merge, Create New, Skip Duplicate". In my case, the "Merge" method will do. Unfortunately, this method will not allow you to perform the classic merging of folders, when the folders are saved and the files are replaced with new ones. Maybe I didn’t figure it out completely, but I didn’t find a way to do something like that.

**Comment by anggrayudi** [comment]
Merging files with Simple Storage does not replace the existed files in the destination. Suppose that I have a folder named `Photo` containing files: A and B. The destination folder named `Pictures` contains P and B. When conflict arises and you select merge, the destination folder will contain A, B, and P, where B from the destination (`Pictures`) is not replaced by the file from the source folder (`Photo`).

Current SimpleStorage's "merge" is actually "merge for all". It does not support classic merging where you can choose which files you want in the destination folder. I'll consider adding this feature in v0.6.0, hope next week. So we can expect the following dialog:

![image](https://user-images.githubusercontent.com/12292380/117526538-1a1c3480-aff0-11eb-99a5-7740e80eaf65.png)

**Comment by DaiZrei** [comment]
> Merging files with Simple Storage does not replace the existed files in the destination. Suppose that I have a folder named `Photo` containing files: A and B. The destination folder named `Pictures` contains P and B. When conflict arises and you select merge, the destination folder will contain A, B, and P, where B from the destination (`Pictures`) is not replaced by the file from the source folder (`Photo`).
> 
> Current SimpleStorage's "merge" is actually "merge for all". It does not support classic merging where you can choose which files you want in the destination folder. I'll consider adding this feature in v0.6.0, hope next week. So we can expect the following dialog:
> 
> ![image](https://user-images.githubusercontent.com/12292380/117526538-1a1c3480-aff0-11eb-99a5-7740e80eaf65.png)

Yes, that's what I mean. Thank you!

**Comment by anggrayudi** [comment]
Please test this version `0.6.0-SNAPSHOT`. Report any bugs to me before I release the stable version. If you want to read the sample code, please checkout branch `release/0.6.0`.

**Comment by DaiZrei** [comment]
I tested this version in my application. I did not find any problems, merging folders with replacing files works fine! I will add 0.6.0-SNAPSHOT to the beta version of my application, if there are any problems, I will write to you. Thanks a lot for this update!

**Comment by anggrayudi** [comment]
Stable version [0.6.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.6.0) has been released.
