### ISSUE TITLE
Read File

### ISSUE THREAD

**Issue by sagarnayak** [anggrayudi/SimpleStorage#27]
I got the callback in filePickerCallback onFileSelected. Now I want to read it and create a preview of this file to show on UI. How can I do that?

Any suggestion?

As of now i am getting

`java.io.FileNotFoundException: /content:/com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FReceived%2FScreenshot_2021-05-12-12-13-57-317_com.android.chrome.jpg: open failed: ENOENT (No such file or directory)`

**Comment by anggrayudi** [comment]
What's your OS version?

**Comment by sagarnayak** [comment]
I have android 10. ROM - Funtoch OS_10.

The stack is exactly as I am getting in my log. it's not changed. I was selecting a file from the Downloads folder in internal storage.

My best guess is that I am missing something in the permissions section. I already am asking for READ and WRITE external storage and also have done this https://github.com/anggrayudi/SimpleStorage#request-storage-access.

**Comment by anggrayudi** [comment]
Can you log the following code for me?
```kotlin
storageHelper.onFileSelected = { requestCode, file ->
    val writableDownloads = if (file.isDownloadsDocument) file.toWritableDownloadsDocumentFile(context) else file
    Log.d(TAG, writableDownloads.uri)
    Log.d(TAG, writableDownloads.isWritable)
    Log.d(TAG, file.isWritable)
}
```
BTW, `writableDownloads` should work after calling `file.toWritableDownloadsDocumentFile(context)`. Try it.

**Comment by sagarnayak** [comment]
>> null
>> null
>> content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FReceived%2FScreenshot_2021-05-12-12-13-57-317_com.android.chrome.jpg
>> true

**Comment by anggrayudi** [comment]
Please try version `0.6.0-SNAPSHOT`. `toWritableDownloadsDocumentFile()` no longer returns null.

**Comment by sagarnayak** [comment]
I am getting uri but the path is blank.

![image](https://user-images.githubusercontent.com/18398903/118758315-70a92e80-b88c-11eb-89cb-a32255cdbd5f.png)

**Comment by anggrayudi** [comment]
Please refresh your dependencies. Follow this instruction: https://stackoverflow.com/a/62085606/3922207

Now it worked for me:

![image](https://user-images.githubusercontent.com/12292380/118785289-ed530180-b8ba-11eb-9734-1c2dba85970b.png)

**Comment by sagarnayak** [comment]
working now. thanks

**Comment by anggrayudi** [comment]
Stable version [0.6.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.6.0) has been released.
