### ISSUE TITLE
Jetpack Compose compatibility

### ISSUE THREAD

**Issue by viktorisacenko** [anggrayudi/SimpleStorage#28]
Hey :) 

Nice work! And thanks very much for the simplificity. 

Are there any plans for compability with jetpack compose / ComponentActivity  to requesting storage access with SimpleStorage

Greets

Viktor

**Comment by anggrayudi** [comment]
I haven't learned Jetpack Compose yet. If you've free time, you can create a pull request. I'll review it. Just checkout from `release/**` branch.

**Comment by anggrayudi** [comment]
Hi @viktorisacenko , can you try `0.10.0-SNAPSHOT`? It supports `ComponentActivity`.

**Comment by anggrayudi** [comment]
The feature has been added in [0.10.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.10.0)
