### ISSUE TITLE
Multiple MIME type

### ISSUE THREAD

**Issue by sagarnayak** [anggrayudi/SimpleStorage#29]
I want to allow users to select only images(jpg, jpeg, png) and pdf files.

i want something like this - 
`storage.openFilePicker(REQUEST_CODE_PICK_FILE,"image/*,application/pdf")`

As of now, I can only select only pdf or only images. not multiple.

**Comment by anggrayudi** [comment]
[0.7.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.7.0) has been released. Check it out!
