### ISSUE TITLE
Unauthorized vendor

### ISSUE THREAD

**Issue by darkman66699** [anggrayudi/SimpleStorage#30]
Library version: 0.x.x
OS version: [Android 10]
Device model: [Samsung S20]

**Describe the bug**
[A clear and concise description of what the bug is]
I did not authorize any added apps applied by a unknown vendor
**To Reproduce**
[Explain the steps to reproduce]

**Stacktrace**
[If applicable]

**Comment by anggrayudi** [comment]
Please edit the description. The issue you reported is unclear.

**Comment by darkman66699** [comment]
Hello and sorry. I did not allow my phone to be rooted and install anything
that was related to the root access. The following
Was not authorized by me and i dont know how to remove anything
Art
VM Version: 2.1.0
Java Home: /system
Class Path: .
Boot Class Path:
/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/com.lge.mdm.jar:/system/framework/com.lge.lgdynamicactionbar.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-location-service.jar:/system/framework/mediatek-ims-base.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar

**Comment by anggrayudi** [comment]
What is this? I think it is unrelated to SimpleStorage.
You do not explain what are you doing in the description. Sorry, I'll close it.
