### ISSUE TITLE
MediaStoreCompat.createAudio() throws NoClassDefFoundError on Android 9

### ISSUE THREAD

**Issue by barantes** [anggrayudi/SimpleStorage#31]
Hi!

I'm trying to create a new audio file using `MediaStoreCompat.createAudio()` so I can write bytes to it using `MediaFile.openOutputStream()`. It works well on Android 11, but when running on Android 9, my code crashes with the following error:

> java.lang.NoClassDefFoundError: Failed resolution of: Landroid/provider/MediaStore$Downloads;
>         at com.anggrayudi.storage.media.MediaType.<clinit>(MediaType.kt:18)
>         at com.anggrayudi.storage.media.MediaStoreCompat.createAudio(MediaStoreCompat.kt:58)

Here's the piece of code that causes the crash:

```
private val fileDesc = FileDescription(name, LIBRARY_FOLDER, MIME_TYPE_WAV)
private val tmpMediaFile: MediaFile? = MediaStoreCompat.createAudio(context, fileDesc, AudioMediaDirectory.MUSIC, true)?.apply {
        isPending = true
    }
```

The problem seems to be that the `MediaType` enum declares the `DOWNLOADS` entry using `MediaStore.Downloads` (added in API level 29), thus making it non-accessible from earlier versions. My expectation was that using `MediaStoreCompat` (and the SimpleStorage library as a whole) would allow me to work with "files" regardless of runtime API versions (or at least with minSDK >= 21). 

Am I missing something? Is there a way to achieve my goal using `MediaStoreCompat` or any other API from SimpleStorage?

Thanks!

```
enum class MediaType(val readUri: Uri, val writeUri: Uri) {
    IMAGE(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, MediaStore.Images.Media.getContentUri(MediaStoreCompat.volumeName)),
    AUDIO(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI, MediaStore.Audio.Media.getContentUri(MediaStoreCompat.volumeName)),
    VIDEO(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, MediaStore.Video.Media.getContentUri(MediaStoreCompat.volumeName)),

    @RequiresApi(Build.VERSION_CODES.Q)
    DOWNLOADS(MediaStore.Downloads.EXTERNAL_CONTENT_URI, MediaStore.Downloads.getContentUri(MediaStoreCompat.volumeName))
}
```

My setup:
```
compileSDKversion = 30
minSDKversion = 21
targetSDKversion = 29
simple_storage_version = '0.5.3'
```

**Comment by anggrayudi** [comment]
Try `0.7.0-SNAPSHOT`

**Comment by barantes** [comment]
Thanks for looking into that. I ended up having to abort using the library due to other reasons, but I looked at 0.7.0-SNAPSHOT's source code and it seems it should work. Thanks!
