### ISSUE TITLE
STORAGE_PERMISSION_DENIED onFailed copying when updating to 0.6.0

### ISSUE THREAD

**Issue by kamdroid3** [anggrayudi/SimpleStorage#35]
Library version: 0.6.0
OS version: [Android 11]
Device model: [Samsung A71]

**Describe the bug**
When using copyFileTo (context, targetFolder, null, callback), it throws the override fun onFailed(errorCode: FileCallback.ErrorCode), with an error STORAGE_PERMISSION_DENIED.

This isn't happening with version 0.5.2

**To Reproduce**
DocumentFile copy to app specific files, not to the shared storage.

**Stacktrace**
[If applicable]

**Comment by anggrayudi** [comment]
Can you log this code on your machine with v0.6.0?
```kotlin
Log.d(TAG, targetFolder.isRawFile)
Log.d(TAG, targetFolder.isWritable)
```

**Comment by kamdroid3** [comment]
Here is the log:

**0.6.0**
```
    target folder is raw file? true
    target folder is writable? false
    target folder absolute path? /data/user/0/<package-name>/files/my_parent_doc_statuses_folder
    source file can read? true

```

**0.5.2**
```
    target folder is raw file? true
    target folder absolute path? /data/user/0/<package-name>/files/my_parent_doc_statuses_folder
    source file can read? true
```

Thank you

**Comment by anggrayudi** [comment]
Current SimpleStorage does not support directory `/data/user/0/<package-name>`. But I'll add this support to `0.7.0`.

**Comment by kamdroid3** [comment]
Great, I will use the 0.5.2 until you release the mentioned version, thank you for your great work.

**Comment by anggrayudi** [comment]
Try `0.7.0-SNAPSHOT`. If this meets your expectation, please close this issue.

**Comment by kamdroid3** [comment]
Yes the `0.7.0-SNAPSHOT` works perfectly, thank you.

**Comment by anggrayudi** [comment]
[0.7.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.7.0) has been released. Check it out!

**Comment by kamdroid3** [comment]
Also works as intended, great work
