### ISSUE TITLE
Error on first permission alert

### ISSUE THREAD

**Issue by billypap1** [anggrayudi/SimpleStorage#37]
Hello, when I have not grant access to the folder, I get the normal alert, I grant access, but I can't get the file.
If I try again I receive the following alert:
"You have no write access to this storage, thus selecting this folder is useless. Would you like to grant access to this folder?"
I don't want to write/move any file, I want only to pick a file.

On second launch of my app, when I try to pick the file, it works fine. I get this only in first time when I grant access.

Is this a bug? Can I restrict it to pick only files, not write/move?

Thanks in advance.

**Comment by anggrayudi** [comment]
[0.7.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.7.0) has been released. Check it out!
