### ISSUE TITLE
onRootPathPermissionGranted called even when user selects the wrong path

### ISSUE THREAD

**Issue by Piyush7890** [anggrayudi/SimpleStorage#40]
Library version: 0.x.x
OS version: [Android 10]
Device model: [Redmi Note 8]

**Describe the bug**
I want to request access for SD card, so I am calling storage.requestStorageAccess(REQUEST_CODE, StorageType.SD_CARD) .
But if user selects the root directory of internal storage, onRootPathPermissionGranted is still being called. 

**To Reproduce**
1) Request SD card storage access
2) Instead of selecting root directory of SD Card, select root directory of Internal storage.
3) onRootPathPermissionGranted  will still be called even though  user has not granted SD card access

**Comment by anggrayudi** [comment]
This is expected, because the second parameter of `requestStorageAccess()` is `initialRootPath`. I'll add a new parameter named `expectedStorageType` on the next release.

**Comment by Piyush7890** [comment]
Great! Thankyou soo much for the library. Requesting storage access had never been this easy :)

**Comment by anggrayudi** [comment]
Version [0.8.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.8.0) has been released.
