### ISSUE TITLE
Not getting file absoulte path

### ISSUE THREAD

**Issue by sagarnayak** [anggrayudi/SimpleStorage#41]
Library version: 0.9.0
OS version: [Android 10]
Device model: [Vivo v11 Pro]

**Describe the bug**
Getting `getAbsolutePath{}` as blank but the name is there.

**To Reproduce**

    implementation "com.anggrayudi:storage:0.9.0"

	private lateinit var storage: SimpleStorageHelper

	storage = SimpleStorageHelper(this)
		storage.onStorageAccessGranted = { _, root ->
			Toast.makeText(
				this,
				getString(
					R.string.ss_selecting_root_path_success_without_open_folder_picker,
					root.getAbsolutePath(this)
				),
				Toast.LENGTH_SHORT
			).show()
		}
			
	storage.onFileSelected = { _, file ->
		Toast.makeText(baseContext, "File selected: ${file.fullName}", Toast.LENGTH_SHORT)
		.show()
		val fileLocation = file.getAbsolutePath(this@UploadDocument)
		logUtil.logV(">>>>> the name is : ${file.name}")
		logUtil.logV(">>>>> if file : ${file.isFile}")
		logUtil.logV(">>>>> the location : $fileLocation")
		gotFile(
			File(fileLocation)
		)
	}

	storage.openFilePicker(REQUEST_CODE_PICK_FILE, "image/*", "application/pdf")

**Stacktrace**

	V: >>>>> the name is : IMG-20210712-WA0000.jpg
	V: >>>>> if file : true
	V: >>>>> the location :

**Comment by anggrayudi** [comment]
`DocumentFile.getAbsolutePath()` returns empty string on some conditions. Usually, it happens when the `DocumentFile` is `androidx.documentfile.provider.SingleDocumentFile` because its URI does not contain any file path. The file path of `SingleDocumentFile` is stored in the SAF database. To access it, you can convert the file to `MediaFile`:
```kotlin
val media = documentFile.toMediaFile(context)
val path = media.absolutePath
```
But there's no guarantee that the SAF will give you the actual path. Personally, I avoid using the absolute path for file management. Normally, an absolute path is used to show useful information to the user, whereas managing files are always with URI.

**Comment by sagarnayak** [comment]
I want to get the absolute path to create a file. I use that file to upload the it to server.

What would you suggest to do here to be able to upload that file to the server?

**Comment by anggrayudi** [comment]
You can read the file via `InputStream`:
```kotlin
file.openInputStream(context)?.use { stream ->
   // upload stream to the server
}
```

**Comment by sagarnayak** [comment]
I also do validation for file type explicitly - for image types and pdf. (can be done with file name)
and a size check which is an issue as of now.
show a preview to the user. (I think this can be done with input stream)
upload to server. (I think can be done with input stream)

can you suggest any method that can give me the size of the file in any way?

**Comment by anggrayudi** [comment]
* For file type, better use `DocumentFile.type` or `DocumentFile.mimeTypeByFileName`.
* For file size, use `DocumentFile.length()` or `val size = Formatter.formatFileSize(context, documentFile.length())`
