### ISSUE TITLE
Why can't I move files from Android/data to internal storage? I have authorized the persistent read and write permissions of Android/data through saf. The error code is no read and write permissions.

### ISSUE THREAD

**Issue by 9292922** [anggrayudi/SimpleStorage#47]
![mmexport1628782758924.png](https://user-images.githubusercontent.com/25112746/129228364-4edaa2d4-fd96-49cf-b697-45289dcd7293.png)

**Comment by 9292922** [comment]
How can I copy files from the Android/data folder to the internal storage space or from the internal storage space to the subdirectory of data/, please give me some advice

**Comment by anggrayudi** [comment]
Closed because no response for long time.

**Comment by 1934291047o** [comment]
> 如何将文件从Android/data文件夹复制到内部存储空间或从内部存储空间复制到data/的子目录，请给我一些建议

兄弟，这个问题你解决了吗，可以给个例子吗

**Comment by 9292922** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我解决了，使用getContentResolver().openInputStream(documentFile.getUri());
    
        
            
        
    
    
    
    

    

    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        07/26/2022 14:00
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [anggrayudi/SimpleStorage] Why can't I move files from Android/data to internal storage? I have authorized the persistent read and write permissions of Android/data through saf. The error code is no read and write permissions. (#47)
        
      
    
  
  



如何将文件从Android/data文件夹复制到内部存储空间或从内部存储空间复制到data/的子目录，请给我一些建议



兄弟，这个问题你解决了吗，可以给个例子吗
