### ISSUE TITLE
Question regarding interoperability

### ISSUE THREAD

**Issue by kairusds** [anggrayudi/SimpleStorage#5]
Is this project interoperable with Java?

**Comment by anggrayudi** [comment]
Please visit this guide: https://github.com/anggrayudi/SimpleStorage/blob/master/JAVA_COMPATIBILITY.md

**Comment by mochadwi** [comment]
You can use e.g: `@file:JvmName("StorageUtils")` above package to rename the `StorageExt`

See below reference:

**Comment by mochadwi** [comment]
You can use e.g: `@file:JvmName("StorageUtils")` above package to rename the `StorageExtKt` so in Java, calling the extensions is prettier imho

See below reference: https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#package-level-functions

Cc @anggrayudi

**Comment by anggrayudi** [comment]
Nice idea @mochadwi. I will add this to the next release. Thanks anyway.
