### ISSUE TITLE
Store PDF from itextpdf

### ISSUE THREAD

**Issue by guenter47** [anggrayudi/SimpleStorage#52]
I use the itextpdf library to create a PDF document. This is an itextpdf document e.g. 'pdfDoc'.
How can I convert this document into DocumentFile that I can store with SimpleStorage?

DocumentFile dfPdf = (DocumentFile) pdfDoc; gives an error: 'Inconvertible types'.

**Comment by anggrayudi** [comment]
What is the type for `pdfDoc`? Is it a `java.io.File`?

**Comment by anggrayudi** [comment]
No response for long time. Closed.
