### ISSUE TITLE
[Java] How can i copy selected file to my app storage on Android 11

### ISSUE THREAD

**Issue by nguyencongbinh** [anggrayudi/SimpleStorage#53]
I would like to copy selected file to PRIVATE_STORAGE on Android 11 to get an allowed file to use later
 ```
storageHelper.setOnFileSelected((integer, documentFiles) -> {
            DocumentFile sourceFile = documentFiles.get(0);
            DocumentFileUtils.copyFileTo(sourceFile, context, **PRIVATE_STORAGE**, null, callBack);
            return null;
        });
```

Can you please help?

**Comment by anggrayudi** [comment]
What is this “private storage”? Can you give me the path?

**Comment by nguyencongbinh** [comment]
It is my app storage path. 
`/storage/sdcard0/Android/data/com.myapp/
`I would like to copy the selected file to my app storage in order to get File/Uri to use later without permission required.

**Comment by anggrayudi** [comment]
Just use `context.getExternalFilesDir()` for that purpose.

```java
      storageHelper.setOnFileSelected((integer, documentFiles) -> {
           DocumentFile sourceFile = documentFiles.get(0);
           DocumentFile privateStorage = DocumentFile.fromFile(context.getExternalFilesDir(null).getPath());
           DocumentFileUtils.copyFileTo(sourceFile, context, privateStorage, null, callBack);
           return null;
       });

```

**Comment by nguyencongbinh** [comment]
It is not working, copying file show black screen forever on device, nothing respond.

**Comment by anggrayudi** [comment]
Please look into the documentation and notice that all functions annotated by `@WorkerThread` should be executed within different thread. `DocumentFileUtils.copyFileTo()` must be executed in background. Read: https://developer.android.com/guide/components/processes-and-threads
