### ISSUE TITLE
AutoIncrementFileName has invalid implementation

### ISSUE THREAD

**Issue by Shusek** [anggrayudi/SimpleStorage#54]
Library version: newest

**Describe the bug**
com.anggrayudi.storage.file.AutoIncrementFileName should not use string comparison like that: ` .maxOfOrNull { it }`.  MaxOf method should be used only for number comparison. At this moment this should be done by search for the biggest number by regex expression.

**To Reproduce**
Folder with two files:
```
SomeFile (9).pdf 
SomeFile (10).pdf
```

autoIncrementFileName method return `SomeFile (10).pdf` as new file instead  `SomeFile (11).pdf`

**Comment by anggrayudi** [comment]
Fixed in [`0.13.0`](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.13.0)

**Comment by Shusek** [comment]
Possibly regression in version 1.3.0.
Now produce  'SomeFile.pdf (1) instead 'SomeFile (1).pdf'.
