### ISSUE TITLE
onFileSelected never run on the launcher Activity

### ISSUE THREAD

**Issue by ahmedsameha1** [anggrayudi/SimpleStorage#55]
Library version: 0.12.0
OS version: Android 11
Device model: Emulator

compileSdkVersion 29
buildToolsVersion '28.0.3'
minSdkVersion 19
targetSdkVersion 29

On my Android project, on the launcher Activity, I use SimpleStorageHelper with onFileSelected. The onFileSelected method never runs.
The project is mainly written in Java, but I have added Kotlin support.

When I create a brand new project in Java, onFileSelected method runs.
When I create a brand new project in Kotlin, onFileSelected method runs.
In the aforementioned project, when I create a new Activity in Java and I use SimpleStorageHelper with onFileSelected in it, then I start this new Activity from the aforementioned Activity, the onFileSelected method runs!!

I have tried to use the Android Studio debugger. The debugger doesn't step into onFileSelected.
I cannot understand where is the problem.

**Comment by anggrayudi** [comment]
Are you using `android.app.Activity` or `AppCompatActivity`? If `AppCompatActivity`, what activity (`androidx.activity:activity`) version do you have in your dependency?

**Comment by anggrayudi** [comment]
Fixed in [`0.13.0`](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.13.0)

**Comment by ahmedsameha1** [comment]
@anggrayudi The problem has been fixed. Thank you for your efforts.
