### ISSUE TITLE
convert documentfile to normal file

### ISSUE THREAD

**Issue by viral9** [anggrayudi/SimpleStorage#56]
**What feature you want to suggest?**
 i want to upload file in server , but my upload mechanism if not supporting documentfile 
 so i want to convert documentfile to file so i can upload file  

**Your solution**
currently i converting path for absolute path and use for upload 
but this is not working each and every time 

**Your current alternative**
i try to find convert documentfile to normal file but there is no solution or didn't get anything that help me

**Comment by anggrayudi** [comment]
You can refer to this issue #41
