### ISSUE TITLE
Question : any possiblety Convert Document File To java.io.File?

### ISSUE THREAD

**Issue by HirenJodhani** [anggrayudi/SimpleStorage#59]
```
val file: File? = documentFile.toRawFile(context)?.takeIf { it.canRead() }
```

but in java project not show documentFile.toRawFile..

**Comment by anggrayudi** [comment]
You can read this [Java Compatibility](https://github.com/anggrayudi/SimpleStorage/blob/master/JAVA_COMPATIBILITY.md) on how to use Kotlin extension functions in Java. In your case, it will be:
```java
DocumentFile file = DocumentFileUtils.toRawFile(documentFile, context); // DocumentFileUtils is an extension class
if (file != null && !file.canRead()) { // takeIf { it.canRead }
    file = null;
}
```
Your life will be easier with Kotlin. I recommend you to learn it.
