### ISSUE TITLE
Trying to download to path 

### ISSUE THREAD

**Issue by DavidKmn** [anggrayudi/SimpleStorage#6]
I'm trying to use a library like Fetch (https://github.com/tonyofrancis/Fetch) to download: photos, videos, audios and documents to the filesystem. What is the correct way to generate a path for simple storage to download to? 

```
findViewById<FloatingActionButton>(R.id.fab).setOnClickListener {
            val tsLong = System.currentTimeMillis() / 1000
            val ts = tsLong.toString()
            val url = "https://unsplash.com/photos/FQq88kJLoyI/download?force=true"
            val mediaFile = MediaStoreCompat.createImage(this, FileDescription("image${ts}.jpg", subFolder = "Bramti Images", mimeType = "image/jpg"), ImageMediaDirectory.PICTURES)
//           val intent = Intent(applicationContext, DownloadService::class.java)
//            intent.putExtra("downloadUrl", url)
              val path = mediaFile!!.absolutePath
//            intent.putExtra("saveFilePath", path)

            enqueueDownload(url, path)
        }
 }
```

```
    private fun enqueueDownload(url: String, filePath: String) {
        request = Request(url, filePath)
        fetch.attachFetchObserversForDownload(request.id, this)
                .enqueue(request, { result -> request = result }, { result -> Log.d("MainActivity", "SingleDownloadActivity Error: %1${result}s") })
    }
```

**Comment by anggrayudi** [comment]
Prior to API 29, you can use direct `filePath` such as `/storage/emulated/0/Download`, but it no longer works on API 29 and higher. You need to use `Uri` or output stream. Here's the common example:
```kotlin
val mediaFile = MediaStoreCompat.createImage(...)
val uri = mediaFile.uri
val outputStream = mediaFile.openOutputStream()
// Then, use Uri or OutputStream to write file
```
After the file is downloaded successfully, do not forget to set `MediaFile.isPending` to `false`. If not, the file wont be visible to user:
```kotlin
mediaFile.isPending = false
```
Check if Fetch supports writing files with `Uri` or `java.io.OutputStream`.

**Comment by DavidKmn** [comment]
Thanks for the response, so Fetch uses the file path, I have tried doing it the way you stated with uri.path for the strring path, however I get a file not found error.

**Comment by DavidKmn** [comment]
<img width="1260" alt="Screenshot 2021-01-14 at 15 47 14" src="https://user-images.githubusercontent.com/35953014/104614080-d176ef00-567f-11eb-835a-0538e0151faa.png">

Looking inside of fetch i see this

**Comment by anggrayudi** [comment]
For API 29+, Android scoped storage limits your access to external storage, even though user has granted the permissions. The only writable path on API 29+ is `context.getExternalFilesDir()`, which will return:
`/storage/emulated/0/Android/data/your_app_package/files`
You can use this path if you don't want to use `Uri` and stick with `java.io.File`.

 If you want to save downloads into media file or public directory like `Download`, then you have to depend on `Uri` or `java.io.OutputStream`.

Yup, `MediaStoreCompat` is for media files only. For documents and other files, you can use `DocumentFileCompat`. Since Fetch uses `java.io.File`, I will assume that it does not support scoped storage yet. You had better creating an issue on Fetch to request scoped storage support for API 29+.

**Comment by DavidKmn** [comment]
Are you saying to use something like this? 

```
val documentFile = DocumentFileCompat.createFile(this, basePath = "Invigo App Documents", mimeType = "document/pdf")!!
documentFile.uri

```
Files stored in `context.getExternalFilesDir() ` get deleted after app uninstall if I am not mistaken, this is not something I would want. In terms of permissions none are needed for MediaStoreCompat file creating right? What about DocumentFileCompat

**Comment by anggrayudi** [comment]
That's because you don't have URI permissions for read & write files. Please use this approach: https://github.com/anggrayudi/SimpleStorage#request-storage-access

Anyway, it's ok if you use `MediaStoreCompat.createDownload`. No URI permission is required, but you cannot resume downloads by using this method since you cannot check the downloaded file size.

**Comment by DavidKmn** [comment]
Do we really need full disk access to enable this feature.. seems not a great user experience, surely we just want downloads folder access.. I have not seen any apps yet ask me to pick a folder like this. What do you thing would be a better UX?

Have you seen what apps like WhatsApp and Telegram do? they have their own folders in the filesystem and then they create subfolders for their content inside there, these folders are persistent over app reinstalls, is this no longer permissible with SAF?

**Comment by anggrayudi** [comment]
Once you select `Download` folder via SimpleStorage's SAF, implicitly you have granted URI for read & write access. Let user pick `Download` folder once, then you will have full disk access under this directory.

**Comment by DavidKmn** [comment]
Thanks for your help, got what I needed to work, will continue exploring SimpleStorage :)

**Comment by DavidKmn** [comment]
Ok so I have given the access as in the example, and still getting null here ...

`val documentFile = DocumentFileCompat.createFile(this, basePath = "Invigo App Documents/doc${ts}.pdf", mimeType = "application/pdf")!!
`

**Comment by anggrayudi** [comment]
Use this code to check if you have access to `Invigo App Documents`. It should be non-null if the folder is writable.
```kotlin
val writable = DocumentFileCompat.getAccessibleRootDocumentFile(context, buildAbsolutePath(PRIMARY, "Invigo App Documents"), requiresWriteAccess = true) != null
```
`DocumentFileCompat.createFile()` returns null if the folder is not writable.

**Comment by DavidKmn** [comment]
What if I just wanted to create a file in the Environment.DIRECTORY_DOCUMENTS and then write to its uri. 
I tried (after giving access) this:
DocumentFileCompat.fromPublicFolder(this, PublicDirectory.DOWNLOADS, subFile = "doc${ts}.pdf", requiresWriteAccess = true)
however this returns null (it does not return null if I omit the subFile parameter, but then I am unclear on how and where to name the file)

**Comment by anggrayudi** [comment]
`DocumentFileCompat.from...()` returns null if you have no URI access. You had better cloning this project and test the code on your own. I will close this issue since the discussion becoming more complex and I have no much time to teach you.
