### ISSUE TITLE
moveFileTo exception on file input stream close

### ISSUE THREAD

**Issue by advplyr** [anggrayudi/SimpleStorage#60]
Running `moveFileTo` in a worker thread, the file moves successfully, but afterwards there is an exception.

`
        documentFile.moveFileTo(ctx, folder, FileDescription(filename, subfolder, MimeType.AUDIO), callback)
`

After `onCompleted` gets called successfully:

> W/System.err: java.io.IOException: close failed: EACCES (Permission denied)
W/System.err:     at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:254)
W/System.err:     at java.io.FileInputStream.close(FileInputStream.java:431)
W/System.err:     at com.anggrayudi.storage.extension.IOUtils.closeStream(IOExt.kt:31)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils.copyFileStream(DocumentFileExt.kt:1948)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils.access$copyFileStream(DocumentFileExt.kt:1)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils$moveFileTo$11.invoke(DocumentFileExt.kt:2082)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils$moveFileTo$11.invoke(DocumentFileExt.kt:2081)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils.createFileStreams(DocumentFileExt.kt:1864)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils.moveFileTo(DocumentFileExt.kt:2081)
W/System.err:     at com.anggrayudi.storage.file.DocumentFileUtils.moveFileTo(DocumentFileExt.kt:2002)

**Comment by eclectice** [comment]
The most typical issue encountered when using a scoped storage model over the Internet is that the `FileInputStream` object is unable to open a file owing to poor permission configuration concerns. However, you have an issue with closing a file because permission has been denied. A worker thread, I presume, has locked the file it is attempting to close.

**Comment by anggrayudi** [comment]
Can you share the URI of the source file, @advplyr ?

**Comment by advplyr** [comment]
URI: `content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FAnatomy%20of%20the%20State%2Faudio.mp3`
SimplePath: `primary:Audiobooks/Anatomy of the State/audio.mp3`

**Comment by anggrayudi** [comment]
The stacktrace can be ignored since the file has been moved successfully. I have renamed function `closeStream()` to `closeStreamQuietly()` to avoid future confusion.
