### ISSUE TITLE
Question : how can i set specific path or uri in storageHelper.openFolderPicker(REQUEST_CODE_PICK_FOLDER);?

### ISSUE THREAD

**Issue by HirenJodhani** [anggrayudi/SimpleStorage#62]
Like this : 
 Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
                intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI,pathuri));
                startActivity(intent);

**Comment by amarilindra** [comment]
Looking for the same. 

I need the folder picker by default open /Download/myfolder

**Comment by anggrayudi** [comment]
Will be included in `0.14.0`. For now, you can use the snapshot version, `0.14.0-SNAPSHOT`

**Comment by anggrayudi** [comment]
Added in [0.14.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/0.14.0)
