### ISSUE TITLE
Cannot retrieve Image after creating it.

### ISSUE THREAD

**Issue by DavidKmn** [anggrayudi/SimpleStorage#7]
I have created an image using the below code.

`val imageMediaFile = MediaStoreCompat.createImage(this, FileDescription("image1.jpg", subFolder = "Imgur Images", mimeType = "image/jpg"), ImageMediaDirectory.PICTURES)!!
`
Later I would get the image back, and I use:

`val fetched = MediaStoreCompat.fromFileNameContains(this, mediaType = MediaType.IMAGE, containsName = "image1.jpg")`

However this always returns null, am I doing something wrong?

**Comment by anggrayudi** [comment]
What is the result if you using `MediaStoreCompat.fromFileName(context, MediaType.IMAGE, "image1.jpg")`?

**Comment by DavidKmn** [comment]
I also get null using that method

**Comment by anggrayudi** [comment]
I've created `0.4.3-SNAPSHOT`. Please try this.

**Comment by anggrayudi** [comment]
This issue has been fixed in branch `release/0.4.3`: https://github.com/anggrayudi/SimpleStorage/commit/875fe1b43bea64237c75c6d259af7b4f926064b7

Let's find another bug and include the fixes on `0.4.3`.
