### ISSUE TITLE
java.io.FileNotFoundException: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by NayabSarfraz** [anggrayudi/SimpleStorage#71]
Library version: 0.9.
OS version: [Android 11]
Device model: [Redmi 5g]

**Describe the bug**
I have requested `primary:Android/media/com.whatsapp/WhatsApp/Media/` Uri permission using **Storage Frame Work** and after that i am listing all document files from a hidden folder inside this which is .Statuses.

I actually want to work with java.io.File so i have used toRaw file to convert this document file to java.io.File and the path of raw file is like this
`/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses/0916765d27ae46b883ca7de728547c2f.jpg
`
The issue is when i load this file to imageview i get  android.system.ErrnoException: open failed: EACCES (Permission denied)

**Below is my Activity Code**
```
package com.example.simplestoragetesting

import android.content.Intent
import android.graphics.drawable.Drawable
import android.net.Uri
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.os.Environment
import android.widget.Button
import android.widget.ImageView
import android.widget.Toast
import androidx.documentfile.provider.DocumentFile
import com.anggrayudi.storage.SimpleStorage
import com.anggrayudi.storage.SimpleStorageHelper
import com.anggrayudi.storage.callback.StorageAccessCallback
import com.anggrayudi.storage.file.*
import com.anggrayudi.storage.media.MediaStoreCompat
import com.anggrayudi.storage.media.MediaType
import com.bumptech.glide.Glide
import com.bumptech.glide.load.DataSource
import com.bumptech.glide.load.engine.GlideException
import com.bumptech.glide.request.RequestListener
import com.bumptech.glide.request.target.Target
import java.io.File

class MainActivity : AppCompatActivity() {
    val REQUEST_CODE_STORAGE_ACCESS = 654
    private lateinit var storageHelper: SimpleStorageHelper

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val btnRequestStorageAccess = findViewById<Button>(R.id.btnRequestStorageAccess)
        val btnOpenFolderPicker = findViewById<Button>(R.id.btnOpenFolderPicker)
        val btnOpenFilePicker = findViewById<Button>(R.id.btnOpenFilePicker)
        val imageView = findViewById<ImageView>(R.id.imageView)

        storageHelper = SimpleStorageHelper(this, savedInstanceState)
        storageHelper.onFolderSelected = { requestCode, folder ->
            // do stuff

            var list = folder?.listFiles()?.forEach {
                if (it.name.equals(".Statuses")) {
                    var filesST = it.listFiles()
                    var abc: DocumentFile = filesST.get(1)

                  //  val path = "${abc.getRootPath(this)}/${abc.getBasePath(this)}"

                    val xyz = abc?.toRawFile(this)
                    Glide.with(this).load(xyz?.absoluteFile)
                        .listener(object :
                            RequestListener<Drawable> {
                            override fun onLoadFailed(
                                e: GlideException?,
                                model: Any?,
                                target: Target<Drawable>?,
                                isFirstResource: Boolean
                            ): Boolean {
                                val exception=e
                                val dfsd="fdsf"
                                // here i get  java.io.FileNotFoundException: open failed: EACCES (Permission denied)
                                return false
                            }

                            override fun onResourceReady(
                                resource: Drawable?,
                                model: Any?,
                                target: Target<Drawable>?,
                                dataSource: DataSource?,
                                isFirstResource: Boolean
                            ): Boolean {
                                return false
                            }
                        }
                        ).into(imageView)
                }
            }

        }
        storageHelper.onFileSelected = { requestCode, file ->
            // do stuff
        }

        btnRequestStorageAccess.setOnClickListener { storageHelper.requestStorageAccess() }
        btnOpenFolderPicker.setOnClickListener { storageHelper.openFolderPicker() }
        btnOpenFilePicker.setOnClickListener { storageHelper.openFilePicker() }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        storageHelper.storage.onActivityResult(requestCode, resultCode, data)
    }

    override fun onSaveInstanceState(outState: Bundle) {
        storageHelper.onSaveInstanceState(outState)
        super.onSaveInstanceState(outState)
    }

    override fun onRestoreInstanceState(savedInstanceState: Bundle) {
        super.onRestoreInstanceState(savedInstanceState)
        storageHelper.onRestoreInstanceState(savedInstanceState)
    }


}
```

**To Reproduce**

- Fetch document file
- getRootPath and getBasePath
- Create file object from resulting path
- Set to imageview, or try to use this file any other way
- Permission denied exception

**Stacktrace**

> I/Glide: Root cause (1 of 3)
>     java.io.FileNotFoundException: /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses/0916765d27ae46b883ca7de728547c2f.jpg: open failed: EACCES (Permission denied)
>         at libcore.io.IoBridge.open(IoBridge.java:492)
>         at java.io.FileInputStream.<init>(FileInputStream.java:160)
>         at java.io.FileInputStream.<init>(FileInputStream.java:115)
>         at android.content.ContentResolver.openInputStream(ContentResolver.java:1498)
>         at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:74)
>         at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:50)
>         at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:13)
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
>         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
>         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
>      Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
>         at libcore.io.Linux.open(Native Method)
>         at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
>         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
>         at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
>         at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7923)
>         at libcore.io.IoBridge.open(IoBridge.java:478)
>         at java.io.FileInputStream.<init>(FileInputStream.java:160) 
>         at java.io.FileInputStream.<init>(FileInputStream.java:115) 
>         at android.content.ContentResolver.openInputStream(ContentResolver.java:1498) 
>         at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:74) 
>         at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:50) 
>         at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:13) 
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44) 
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70) 
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63) 
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) 
>         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) 
>         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:923) 
>         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393) 
> I/Glide: Root cause (2 of 3)
>     java.io.FileNotFoundException: open failed: EACCES (Permission denied)
>         at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:344)
>         at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:231)
>         at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1818)
>         at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1739)
>         at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:20)
>         at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:12)
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
>         at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:412)
>         at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailedInternal(SourceGenerator.java:160)
>         at com.bumptech.glide.load.engine.SourceGenerator$1.onLoadFailed(SourceGenerator.java:83)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:167)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:50)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
>         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
>         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
>     Root cause (3 of 3)
>     java.io.FileNotFoundException: open failed: EACCES (Permission denied)
>         at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:344)
>         at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:231)
>         at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1818)
>         at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1739)
>         at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:20)
>         at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:11)
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
>         at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:412)
>         at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailedInternal(SourceGenerator.java:160)
>         at com.bumptech.glide.load.engine.SourceGenerator$1.onLoadFailed(SourceGenerator.java:83)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:167)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:50)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
>         at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:412)
>         at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailedInternal(SourceGenerator.java:160)
>         at com.bumptech.glide.load.engine.SourceGenerator$1.onLoadFailed(SourceGenerator.java:83)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:167)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
>         at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:50)
>         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
>         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
>         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
>         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
>         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
> I/mple.saftestin: ProcessProfilingInfo new_methods=2222 is saved saved_to_disk=1 resolve_classes_delay=8000
> V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@5940362, this = DecorView@8d97cf3[MainActivity]

How can i get java.io.File object from a DocumentFile using this library. Can somebody please help me out with this? 

Any help will be appreciated

Thank you

**Comment by nicolabeghin** [comment]
Any update on this?

**Comment by anggrayudi** [comment]
Do not use `java.io.File` or direct file paths on Android 10 and higher. Use extension function `makeFile()` or `makeFolder()` instead.
```kotlin
storageHelper.onFolderSelected = { requestCode, folder ->
   val newFile = folder.makeFile(context, filename, "image/jpg")
}
```

**Comment by yogithesymbian** [comment]
> .absolu

how about these one
```

        storageHelper.onFileSelected = { requestCode, files ->
            val file = files.first()
            when (requestCode) {
               REQUEST_CODE_SELECT_FILE -> {
                    Log.d("SIMPLE_STORAGE", "file : ${file.fullName}")
                    val newFile = file.makeFile(requireContext(), file.fullName, "${file.mimeType}") // this always on null

                    myFile = File(file.getAbsolutePath(requireContext()) // i need to set DocumentFile into File
                 }
              }
         }

....
var myFile: File? = null
....
```

same problem ( android 11 )
```
 onError errorDetail : com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: java.io.FileNotFoundException: /storage/emulated/0/Custom/file.pdf: open failed: EACCES (Permission denied)
```
before i request the storage by 
```
storageHelper.requestStorageAccess(
            requestCode = REQUEST_CODE_STORAGE_ACCESS,
            initialRootPath = StorageType.EXTERNAL,
            expectedStorageType = StorageType.EXTERNAL,
            // expectedBasePath = "Download"
        ) // more specify
```
