### ISSUE TITLE
Unable to filter files of custom extensions 

### ISSUE THREAD

**Issue by ptatiya** [anggrayudi/SimpleStorage#73]
Hello Team,

  I am using this library for file picker purpose but unable to filter files of custom extensions. Getting error message "storage access framework is currently not available " 

I am using this line of code for filter files of custom extensions. My custom files extension is   .rio  

 storageHelper.openFilePicker(REQUEST_CODE_PICK_FILE,false,".rio");

Anyone can you please help me how filter files of custom extensions using this library.

I am using updated version of library.

**Comment by anggrayudi** [comment]
```kotlin
storageHelper.openFilePicker(requestCode, allowMultiple, filterMimeTypes);
```
The third argument (`.rio`) is not a mime type. It should be something like `image/png`. Please refer to this list: https://www.sitepoint.com/mime-types-complete-list/

**Comment by ptatiya** [comment]
Can we filter custom file extension in this library..?

**Comment by anggrayudi** [comment]
Currently, Android system does not recognize mime type for file extension `*.rio`, so this library can't filter this extension as well.
