### ISSUE TITLE
android  data folder not showing 

### ISSUE THREAD

**Issue by yoonusc** [anggrayudi/SimpleStorage#75]
Library version: latest
OS version: [Android 11]
Device model: [Samsung MO1]
[](url)
**Describe the bug**
[file  picker not showing android data folder ]

**To Reproduce**
[[helper.openfilePicker()]](url)

**Comment by anggrayudi** [comment]
Indeed, this folder is hidden by Android operating system due to security reason, because it contains sensitive file, such as database and preference files.
