### ISSUE TITLE
Wrong name when file does already exist

### ISSUE THREAD

**Issue by fm-sys** [anggrayudi/SimpleStorage#76]
Library version: 0.14.0
OS version: Android 10
Device model: Huawei Mate 20 lite

**Describe the bug**
When creating a new file while a file with the same name does already exist, the "(2)" is added at the wrong place:

Instead of `"A file.apk (2)"` it should be `"A file (2).apk"`

The bug might be MIME type dependent / might happen if the MIME type is `null`. Haven't analyzed the issue further yet...

![Screenshot_20211230_185942_com android documentsui](https://user-images.githubusercontent.com/64581222/147777059-9e2131a8-5a50-4a52-9ed4-30d060f8c159.png)

PS: happened in my App "Snapdrop for Android" / https://github.com/fm-sys/snapdrop-android

**Comment by anggrayudi** [comment]
Fixed in [1.0.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/1.0.0)
