### ISSUE TITLE
How to get the file after selection

### ISSUE THREAD

**Issue by karan-opayn** [anggrayudi/SimpleStorage#77]
Library version: 0.x.x
OS version: [Android 10]
Device model: [Samsung S20]

**Describe the bug**
[A clear and concise description of what the bug is]

**To Reproduce**
[Explain the steps to reproduce]

**Stacktrace**
[If applicable]

**Comment by anggrayudi** [comment]
`onFileSelected` already returns the file object as `DocumentFile`. Please jump into this line: https://github.com/anggrayudi/SimpleStorage/blob/9a154e47d237887abf203337297deb9f18ec2d6e/sample/src/main/java/com/anggrayudi/storage/sample/activity/MainActivity.kt#L125
