### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by tihiydo** [anggrayudi/SimpleStorage#78]
I searched all internet and find this repo, but i don't know kotlin ;))))

Guys can you in future create SAF Java repo?

**Comment by anggrayudi** [comment]
Please read this section: [I have Java projects, but this library is built in Kotlin. How can I use it?](https://github.com/anggrayudi/SimpleStorage/blob/master/FAQ.md#i-have-java-projects-but-this-library-is-built-in-kotlin-how-can-i-use-it)
