### ISSUE TITLE
Cannot detect usb mass storage volume

### ISSUE THREAD

**Issue by Skys777** [anggrayudi/SimpleStorage#8]
Does simple storage support detect usb mass storage? such as usb pen drive or hdd external storage devices.
when i try listing using DocumentFileCompat.getStorageIds(context), it only shows storage volume in /storage/...

Any suggestion read/write file from/to usb mass storage? or this SimpleStorage library will extend to usb mass storage reader also?

**Comment by anggrayudi** [comment]
Currently, this library does not support USB mass storage. But I will add this capability on the next release.

**Comment by Skys777** [comment]
@anggrayudi ok thanks. wait for next release.
btw, is it possible read by URI to file in USB mass storage (e.g sandisk)? currently in android 10, i used the manual inputstream method to read the file. cause i read some posts in SO or other article it is not possible to write to external usb mass storage due to API >= 29 goole change restriction on read and write file to android storage system.

**Comment by anggrayudi** [comment]
I can't promise this support to be added soon, since handling USB mass storage is more complex than I imagined. Current SimpleStorage does not support read & write access to the USB mass storage.

**Comment by Skys777** [comment]
ok noted. thanks for the helpful library.
