### ISSUE TITLE
Open file picker path getting empty

### ISSUE THREAD

**Issue by ptatiya** [anggrayudi/SimpleStorage#80]
Hello Team,

     I am using library for file picker absolute path when i used  **storageHelper.openFilePicker(REQUEST_CODE_PICK_FILE);** for file picker it opens by default recent tab and if we pick file from recent tab path getting empty 

uses this method for absolute path 

storageHelper.setOnFileSelected((requestCode, files) -> {
                 path =  DocumentFileUtils.getAbsolutePath(files.get(0),getApplicationContext());               
                 return null;
            });

but when pick file from recent tab path getting empty can you please help me for this

**Comment by anggrayudi** [comment]
This is the question of a thousand people. Even after I created [FAQs](https://github.com/anggrayudi/SimpleStorage/blob/master/FAQ.md), people are still questioning it.
Please read: [File path returns empty string](https://github.com/anggrayudi/SimpleStorage/blob/master/FAQ.md#file-path-returns-empty-string). There's no guarantee that you will always get the file path for `SingleDocumentFile`.
