### ISSUE TITLE
Need help to read sqlite database

### ISSUE THREAD

**Issue by binu8051** [anggrayudi/SimpleStorage#82]
Hi
In my app i use large size of sqlite database, so i directly copy the files to Documents folder of internal memory.
i am trying to use this library and i use the `storageHelper.openFolderPicker(2, new FileFullPath(this, "/storage/emulated/0/Documents"));` to select the folder, now how to open the database and to use it

This is my code for reading the db which i used before sdk 30
`mypath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).toString() + "/mydb.sqlite";
database = SQLiteDatabase.openDatabase(myPath, Utils.getpw(), null, SQLiteDatabase.OPEN_READONLY);`

also i need to read the content of a dat file from the Documents folder, which code i need to use after i got the folder permisssion?
Anybody help me please.

**Comment by anggrayudi** [comment]
`SQLiteDatabase.openDatabase()` only accepts `String` path or `java.io.File`:

<img width="627" alt="Screen Shot 2022-02-12 at 02 48 31" src="https://user-images.githubusercontent.com/12292380/153659909-49c9d252-9357-4edb-870d-d9139ef68e8e.png">

There's no option to read database from `InputStream`, thus it is not possible to read the database file from path `storage/emulated/0/Documents`. The only accessible path is your own app private directory, i.e. `storage/emulated/0/Android/data/<your-package-name>`. You can use this path like this:

```kotlin
val privateDir = context.getExternalFilesDir(null)
val database = SQLiteDatabase.openDatabase(privateDir, ...)
```
