### ISSUE TITLE
How can i store my app generated images and pdf to users local storage 

### ISSUE THREAD

**Issue by gulabsagevadiya** [anggrayudi/SimpleStorage#84]
How can I store my app generated images and pdf documents in users download/AppName/document type/FinalFile like images and pdfs 
does this lib provide this function?
if yes then how can i achive this task with the help of this lib

Also if possible then i want to store my data in direct folder like whatsapp does. not in download folder

**Comment by anggrayudi** [comment]
I have no idea how WhatsApp can create folder `/storage/emulated/0/WhatsApp` without scoped storage permission. It is also discussed here, and still no answer: [How does other app like (whatsapp, facebook) work without implement scoped storage](https://stackoverflow.com/questions/68715654/how-does-other-app-like-whatsapp-facebook-work-without-implement-scoped-stora)

My assumptions is phone manufactures whitelisted WhatsApp to create `WhatsApp` folder. Maybe they allows specific app packages or some checksum fingerprints to ignore scoped storage restriction.

**Comment by anggrayudi** [comment]
BTW, you can write files into `Download` folder:

```kotlin
val inputStream: InputStream? = ...
val fileDesc = FileDescription("fileName", "AppName", "application/pdf")
val pdf = DocumentFileCompat.createDownloadWithMediaStoreFallback(this, fileDesc)
pdf?.openOutputStream(this)?.write(inputStream.readBytes())
```

No permission required for API 30+, but you need to request runtime permission (`READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`) in API 29-.
