### ISSUE TITLE
STORAGE_PERMISSION_DENIED onFailed copying from Download folder to Documents folder

### ISSUE THREAD

**Issue by binu8051** [anggrayudi/SimpleStorage#87]
Library version: 1.1.0
OS version: [Android 10]
Device model: [Lenova Tab M10 HD]

**Describe the bug**
i got STORAGE_PERMISSION_DENIED  error when copying a file from Download folder to Documents folder

```
File dest = new File("/storage/emulated/0/Documents/");
DocumentFile destinationFolder = DocumentFile.fromFile(dest);
DocumentFileUtils.copyFileTo(sourcefile, getApplicationContext(), destinationFolder, null, new FileCallback()
```

when i use the destination folder as 
File dest = new File(getFilesDir(), "/");
its working fine. i cant use the Document folder as destination.
i have both Read and Write permissions.

**Comment by anggrayudi** [comment]
Have you requested the URI permissions with `SimpleStorageHelper.requestStorageAccess()` for `Download` and `Documents` folders?

**Comment by anggrayudi** [comment]
Closed. Inactive for too long.

**Comment by tree1891** [comment]
Does it need permission for Download  and Documents?
