### ISSUE TITLE
Absolute or full file path return blank.

### ISSUE THREAD

**Issue by Dhaval3344** [anggrayudi/SimpleStorage#89]
Library version: 1.3.0
OS version: [Android 11]
Device model: [Google Pixel 4a]

I pick the image and try to get the image absolute path but not working, please check the below code:
filePath = DocumentFileUtils.getAbsolutePath(files.get(0), requireContext())

Using the above line path gets blank, check below attach SS.

![Screenshot 2022-04-18 161547](https://user-images.githubusercontent.com/53849762/163800144-48f815f9-6649-4019-b112-57dfbc16ccc3.png)

**Comment by anggrayudi** [comment]
Retrieving absolute path on scoped storage is useless. Even though you have success to get the path, you can't do anything because scoped storage allows file management with URI only. Please read FAQ [File path returns empty string](https://github.com/anggrayudi/SimpleStorage/blob/master/FAQ.md#file-path-returns-empty-string)

**Comment by anggrayudi** [comment]
I can't understand why people forcing me to make this library works with direct file paths. This library is just a wrapper for the scoped storage APIs. I have mentioned in the FAQ that **it is not the library limitation, but the operating system itself**. So, if you want to make your apps works well with direct file paths (`java.io.File`), you only have 3 options:

1. Request full disk access. Read: [Manage all files on a storage device](https://developer.android.com/training/data-storage/manage-all-files)
2. Ask Google to remove the scoped storage restrictions.
3. Try to create a pull request to Android Open Source Projects. I wish your PR will be approved by Google.

This library is a trash for people who don't understand how scoped storage works. You can search other libraries that manage scoped storage like Simple Storage. Unfortunately, they report the same thing as I have faced.

**Comment by Tanzin01** [comment]
Well,  this scoped storage is trash...... so is shitty ggle.
