### ISSUE TITLE
Can't get the permisson for "Documents" directory on Android 10

### ISSUE THREAD

**Issue by CXStudioTeam** [anggrayudi/SimpleStorage#90]
Can't get the permisson using storage.requestStorageAccess() for Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS). 

**override fun onRootPathPermissionGranted(requestCode: Int, root: DocumentFile) {

 }**

The above callback, get path from root is **/storage/home** , uri : content://com.android.externalstorage.documents/tree/home%3A/document/home%3A. Obviously it was wrong.

**The reuslt  On Andorid 11**
path: /storage/emulated/0/Documents 
uri: content://com.android.externalstorage.documents/tree/primary%3ADocuments/document/primary%3ADocuments

The result on Android 11 was right.

**Comment by anggrayudi** [comment]
Version [1.4.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/1.4.0) has been released.
