### ISSUE TITLE
手机自带的文件管理器中手动删除之后，不会再在该目录下创建相同文件名的文件

### ISSUE THREAD

**Issue by WDevaloper** [anggrayudi/SimpleStorage#91]
针对Android Q及以上版本 , 在公共目录指定文件夹下创建了文件，比如在“Download/TestDir”中创建了文件，如果用户在手机自带的文件管理器中手动删除之后，不会再在该目录下创建相同文件名的文件？这是为什么？有解决方案吗？

**Comment by anggrayudi** [comment]
English please

**Comment by WDevaloper** [comment]
For Android Q and above, a file is created in the specified folder of the public directory, for example, a file is created in "Download/TestDir". Create a file with the same file name in the directory? why is that? Is there a solution?

**Comment by WDevaloper** [comment]
> For Android Q and above, a file is created in the specified folder of the public directory, for example, a file is created in "Download/TestDir". Create a file with the same file name in the directory? why is that? Is there a solution?



> English please

For Android Q and above, a file is created in the specified folder of the public directory, for example, a file is created in "Download/TestDir". Create a file with the same file name in the directory? why is that? Is there a solution?

**Comment by anggrayudi** [comment]
So, what's the issue? I don't get it.

**Comment by anggrayudi** [comment]
Inactive for too long. Closed.
