### ISSUE TITLE
Choosing initial Path for file picker and requestStorageAcess

### ISSUE THREAD

**Issue by Shashank066** [anggrayudi/SimpleStorage#98]
Is there an option to choose file picker and requestStorageAccess initial path?

For requestStorageAcess choosing between sd Card and internal storage is possible using
```
StorageType.EXTERNAL 
StorageType.SD_CARD
```

Is more precise path possible?
Also for file picker I don't see any option to choose even sd card or internal storage.

**Comment by anggrayudi** [comment]
Added in version [1.5.0](https://github.com/anggrayudi/SimpleStorage/releases/tag/1.5.0).

Here's the example:
```kotlin
// this constructor only supports API 30+
val fullPath = FileFullPath(context, StorageType.EXTERNAL, "DCIM")

// for API 29 and lower, you can:
val fullPath = FileFullPath(context, StorageId.PRIMARY, "DCIM")

storageHelper.requestStorageAccess(initialPath = fullPath)
storageHelper.openFolderPicker(initialPath = fullPath)
```
